# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_questions = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_questions.setGeometry(QtCore.QRect(10, 40, 481, 281))
        self.listWidget_questions.setObjectName("listWidget_questions")
        self.label_questions = QtWidgets.QLabel(self.centralwidget)
        self.label_questions.setGeometry(QtCore.QRect(10, 20, 81, 17))
        self.label_questions.setObjectName("label_questions")
        self.listWidget_false_answers = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_false_answers.setGeometry(QtCore.QRect(530, 220, 260, 100))
        self.listWidget_false_answers.setObjectName("listWidget_false_answers")
        self.label_false_answers = QtWidgets.QLabel(self.centralwidget)
        self.label_false_answers.setGeometry(QtCore.QRect(530, 200, 111, 17))
        self.label_false_answers.setObjectName("label_false_answers")
        self.label_true_answer = QtWidgets.QLabel(self.centralwidget)
        self.label_true_answer.setGeometry(QtCore.QRect(530, 140, 101, 17))
        self.label_true_answer.setObjectName("label_true_answer")
        self.lineEdit_true_answer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_true_answer.setGeometry(QtCore.QRect(530, 160, 260, 25))
        self.lineEdit_true_answer.setObjectName("lineEdit_true_answer")
        self.lineEdit_class = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_class.setGeometry(QtCore.QRect(530, 40, 260, 25))
        self.lineEdit_class.setObjectName("lineEdit_class")
        self.label_class = QtWidgets.QLabel(self.centralwidget)
        self.label_class.setGeometry(QtCore.QRect(530, 20, 51, 17))
        self.label_class.setObjectName("label_class")
        self.lineEdit_chapter = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_chapter.setGeometry(QtCore.QRect(530, 100, 260, 25))
        self.lineEdit_chapter.setObjectName("lineEdit_chapter")
        self.label_chapter = QtWidgets.QLabel(self.centralwidget)
        self.label_chapter.setGeometry(QtCore.QRect(530, 80, 71, 17))
        self.label_chapter.setObjectName("label_chapter")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(490, 40, 21, 21))
        self.pushButton_add.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButton_add.setIcon(icon)
        self.pushButton_add.setFlat(False)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_edit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_edit.setGeometry(QtCore.QRect(490, 60, 21, 21))
        self.pushButton_edit.setText("")
        self.pushButton_edit.setFlat(False)
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(490, 80, 21, 21))
        self.pushButton_delete.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButton_delete.setIcon(icon)
        self.pushButton_delete.setFlat(False)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.label_preview = QtWidgets.QLabel(self.centralwidget)
        self.label_preview.setGeometry(QtCore.QRect(10, 340, 67, 17))
        self.label_preview.setObjectName("label_preview")
        self.textBrowser_preview = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_preview.setGeometry(QtCore.QRect(10, 359, 781, 181))
        self.textBrowser_preview.setObjectName("textBrowser_preview")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_about = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.action_about.setIcon(icon)
        self.action_about.setObjectName("action_about")
        self.action_quit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.action_quit.setIcon(icon)
        self.action_quit.setObjectName("action_quit")
        self.action_undo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-undo")
        self.action_undo.setIcon(icon)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-redo")
        self.action_redo.setIcon(icon)
        self.action_redo.setObjectName("action_redo")
        self.action_cut = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-cut")
        self.action_cut.setIcon(icon)
        self.action_cut.setObjectName("action_cut")
        self.action_copy = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.action_copy.setIcon(icon)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-paste")
        self.action_paste.setIcon(icon)
        self.action_paste.setObjectName("action_paste")
        self.action_delete = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-delete")
        self.action_delete.setIcon(icon)
        self.action_delete.setObjectName("action_delete")
        self.action_select_all = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-select-all")
        self.action_select_all.setIcon(icon)
        self.action_select_all.setObjectName("action_select_all")
        self.menuFile.addAction(self.action_quit)
        self.menu_Edit.addAction(self.action_undo)
        self.menu_Edit.addAction(self.action_redo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_cut)
        self.menu_Edit.addAction(self.action_copy)
        self.menu_Edit.addAction(self.action_paste)
        self.menu_Edit.addAction(self.action_delete)
        self.menu_Edit.addAction(self.action_select_all)
        self.menu_Help.addAction(self.action_about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listWidget_questions, self.lineEdit_class)
        MainWindow.setTabOrder(self.lineEdit_class, self.lineEdit_chapter)
        MainWindow.setTabOrder(self.lineEdit_chapter, self.lineEdit_true_answer)
        MainWindow.setTabOrder(self.lineEdit_true_answer, self.listWidget_false_answers)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quiz"))
        self.label_questions.setText(_translate("MainWindow", "Questions:"))
        self.label_false_answers.setText(_translate("MainWindow", "False Answers:"))
        self.label_true_answer.setText(_translate("MainWindow", "True Answer:"))
        self.label_class.setText(_translate("MainWindow", "Class:"))
        self.label_chapter.setText(_translate("MainWindow", "Chapter:"))
        self.pushButton_add.setStatusTip(_translate("MainWindow", "Add question"))
        self.pushButton_edit.setStatusTip(_translate("MainWindow", "Edit question"))
        self.pushButton_delete.setStatusTip(_translate("MainWindow", "Delete question"))
        self.label_preview.setText(_translate("MainWindow", "Preview:"))
        self.textBrowser_preview.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Class</span>: Human Biology 1170</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Chapter</span>: 19</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">How much wood could a woodchuck chuck if a woodchuck could chuck wood?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    A. About as much wood as a woodchuck could chuck if a woodchuck could chuck wood</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    B. 4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    C. False</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    D. All of the above</p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.action_about.setText(_translate("MainWindow", "About Quiz..."))
        self.action_quit.setText(_translate("MainWindow", "&Quit"))
        self.action_quit.setStatusTip(_translate("MainWindow", "Quit application"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_undo.setText(_translate("MainWindow", "Undo"))
        self.action_redo.setText(_translate("MainWindow", "Redo"))
        self.action_cut.setText(_translate("MainWindow", "Cu&t"))
        self.action_copy.setText(_translate("MainWindow", "&Copy"))
        self.action_paste.setText(_translate("MainWindow", "&Paste"))
        self.action_delete.setText(_translate("MainWindow", "&Delete"))
        self.action_select_all.setText(_translate("MainWindow", "Select &All"))

